### ISSUE TITLE
Thanks for the great work! I Got this error when I run vagrant up

### ISSUE THREAD

**Issue by joshzinny** [carrossoni/CDPDCTrial#1]
default: 2020-12-09 00:31:12,978 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2657902450>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /api/v40/cm/commands/hostInstall
    default: 2020-12-09 00:33:20,210 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2657902890>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /api/v40/cm/commands/hostInstall
    default: 2020-12-09 00:35:27,442 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2657902a10>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /api/v40/cm/commands/hostInstall
    default: Traceback (most recent call last):
    default:   File "/root/CDPDCTrial/scripts/create_cluster.py", line 63, in <module>
    default:     cmd = cm_api.host_install_command(body=instargs)
    default:   File "/usr/lib/python2.7/site-packages/cm_client/apis/cloudera_manager_resource_api.py", line 1914, in host_install_command
    default:     (data) = self.host_install_command_with_http_info(**kwargs)
    default:   File "/usr/lib/python2.7/site-packages/cm_client/apis/cloudera_manager_resource_api.py", line 1992, in host_install_command_with_http_info
    default:     collection_formats=collection_formats)
    default:   File "/usr/lib/python2.7/site-packages/cm_client/api_client.py", line 326, in call_api
    default:     _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    default:   File "/usr/lib/python2.7/site-packages/cm_client/api_client.py", line 153, in __call_api
    default:     _request_timeout=_request_timeout)
    default:   File "/usr/lib/python2.7/site-packages/cm_client/api_client.py", line 371, in request
    default:     body=body)
    default:   File "/usr/lib/python2.7/site-packages/cm_client/rest.py", line 263, in POST
    default:     body=body)
    default:   File "/usr/lib/python2.7/site-packages/cm_client/rest.py", line 163, in request
    default:     headers=headers)
    default:   File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 79, in request
    default:     method, url, fields=fields, headers=headers, **urlopen_kw
    default:   File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    default:     return self.urlopen(method, url, **extra_kw)
    default:   File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    default:     response = conn.urlopen(method, u.request_uri, **kw)
    default:   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    default:     **response_kw
    default:   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    default:     **response_kw
    default:   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    default:     **response_kw
    default:   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    default:     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    default:   File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 573, in increment
    default:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    default: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='cloudera', port=7180): Max retries exceeded with url: /api/v40/cm/commands/hostInstall (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2657902b10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
    default: usermod: group 'hadoop' does not exist
    default: sudo: unknown user: hdfs
    default: sudo: unable to initialize policy plugin
    default: sudo: unknown user: hdfs
    default: sudo: unable to initialize policy plugin
    default: sudo: unknown user: hdfs
    default: sudo: unable to initialize policy plugin
    default: sudo: unknown user: hdfs
    default: sudo: unable to initialize policy plugin
    default: sudo: unknown user: hdfs
    default: sudo: unable to initialize policy plugin

Note: I am also not sure what the VM username and password is, as I can't access the box.
I have tried the following:
-u cloudera -p cloudera
-u root -p root
-u admin -p admin
-u cloudera -p root
-u root - p cloudera

**Comment by carrossoni** [comment]
Hi @joshzinny sorry for the delay since I wasn't looking here directly (only in the community post) and I'm updating now for the latest CDP Version. Did you pass this issue?

To login in the ssh box you don't need the password, you can do directly using "vagrant ssh" command. Let me know if you've more questions.
